const eventData = [
    {
        title: "Tech Innovators Conference",
        dateO: "2024-01-15T10:00:00.000Z",
        name: "TechWorld Events",
        time: "10:00AM - 4:00PM",
        category: "Technology",
        mode: "Hybrid",
        venue: "TechHub Center",
        city: "San Francisco",
        country: "USA",
        description: "A gathering of leading innovators to discuss the latest in technology.",
        eligibility: "Open to all tech enthusiasts",
        paticipantCount: 200,
        price: 49.99,
        img: "https://example.com/event1.jpg",
        caption: "Empowering the Future of Tech!"
    },
    {
        title: "Healthcare Summit 2024",
        dateO: "2024-03-10T09:00:00.000Z",
        name: "HealthCon",
        time: "9:00AM - 5:00PM",
        category: "Healthcare",
        mode: "Virtual",
        venue: "Online",
        city: "New York",
        country: "USA",
        description: "Discussing advancements in healthcare and medicine.",
        eligibility: "Healthcare professionals",
        paticipantCount: 500,
        price: 29.99,
        img: "https://example.com/event2.jpg",
        caption: "The Future of Healthcare"
    },
    {
        title: "Sustainability Workshop",
        dateO: "2024-05-22T08:00:00.000Z",
        name: "GreenEarth Org",
        time: "8:00AM - 12:00PM",
        category: "Environment",
        mode: "In-Person",
        venue: "Green Convention Center",
        city: "Seattle",
        country: "USA",
        description: "A workshop on sustainable practices and eco-friendly solutions.",
        eligibility: "Open to everyone",
        paticipantCount: 150,
        price: 19.99,
        img: "https://example.com/event3.jpg",
        caption: "Building a Sustainable Future"
    },
    {
        title: "AI and Robotics Expo",
        dateO: "2024-07-15T10:00:00.000Z",
        name: "AIWorld",
        time: "10:00AM - 6:00PM",
        category: "Technology",
        mode: "Hybrid",
        venue: "Robot Hall",
        city: "Boston",
        country: "USA",
        description: "An exhibition showcasing the latest in AI and robotics.",
        eligibility: "Open to all",
        paticipantCount: 300,
        price: 59.99,
        img: "https://example.com/event4.jpg",
        caption: "The Future of AI and Robotics"
    },
    {
        title: "Food and Beverage Expo",
        dateO: "2024-09-18T11:00:00.000Z",
        name: "FoodFest",
        time: "11:00AM - 8:00PM",
        category: "Food & Beverage",
        mode: "In-Person",
        venue: "Gourmet Center",
        city: "Chicago",
        country: "USA",
        description: "A celebration of food and beverages from around the world.",
        eligibility: "Open to all food lovers",
        paticipantCount: 400,
        price: 39.99,
        img: "https://example.com/event5.jpg",
        caption: "A Feast for the Senses"
    },
    {
        title: "Startup Pitch Night",
        dateO: "2024-11-05T18:00:00.000Z",
        name: "Startup Central",
        time: "6:00PM - 10:00PM",
        category: "Business",
        mode: "In-Person",
        venue: "Innovation Hub",
        city: "San Francisco",
        country: "USA",
        description: "Entrepreneurs pitch their ideas to investors and industry leaders.",
        eligibility: "Startups and investors",
        paticipantCount: 100,
        price: 0,
        img: "https://example.com/event6.jpg",
        caption: "Pitch, Partner, Prosper"
    },
    {
        title: "Music and Arts Festival",
        dateO: "2024-08-20T12:00:00.000Z",
        name: "Artistry Events",
        time: "12:00PM - 10:00PM",
        category: "Arts & Culture",
        mode: "In-Person",
        venue: "Central Park",
        city: "New York",
        country: "USA",
        description: "A festival celebrating music and arts with performances and exhibits.",
        eligibility: "Open to all",
        paticipantCount: 500,
        price: 29.99,
        img: "https://example.com/event7.jpg",
        caption: "A Symphony of Creativity"
    },
    {
        title: "Fitness Bootcamp",
        dateO: "2024-06-15T07:00:00.000Z",
        name: "FitLife",
        time: "7:00AM - 11:00AM",
        category: "Health & Fitness",
        mode: "In-Person",
        venue: "Fitness Park",
        city: "Miami",
        country: "USA",
        description: "An intensive fitness bootcamp led by top trainers.",
        eligibility: "Fitness enthusiasts",
        paticipantCount: 100,
        price: 19.99,
        img: "https://example.com/event8.jpg",
        caption: "Train Hard, Stay Fit"
    },
    {
        title: "Tech Career Fair",
        dateO: "2024-04-10T09:00:00.000Z",
        name: "Career Pathways",
        time: "9:00AM - 5:00PM",
        category: "Career",
        mode: "Hybrid",
        venue: "Convention Center",
        city: "Austin",
        country: "USA",
        description: "Connect with top tech companies and explore career opportunities.",
        eligibility: "Job seekers",
        paticipantCount: 300,
        price: 0,
        img: "https://example.com/event9.jpg",
        caption: "Your Future in Tech"
    },
    {
        title: "Gaming Expo 2024",
        dateO: "2024-10-28T10:00:00.000Z",
        name: "Game World",
        time: "10:00AM - 7:00PM",
        category: "Gaming",
        mode: "Hybrid",
        venue: "Gaming Arena",
        city: "Los Angeles",
        country: "USA",
        description: "Explore the latest in gaming technology and meet industry leaders.",
        eligibility: "Gamers and developers",
        paticipantCount: 450,
        price: 34.99,
        img: "https://example.com/event10.jpg",
        caption: "Level Up Your Gaming Experience"
    }
];

module.exports = {data : eventData};
